project:
  type: website
  output-dir: docs

website:
  title: "Andrew Zieffler"
  site-url: "https://datadreaming.org"
  repo-url: "https://www.github.com/zief0002/data-dreaming-quarto"
  body-header: "/assets/body-header.qmd"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact
      - href: "https://datadreaming.org/files/zieffler-cv.pdf"
        text: CV
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: posts.qmd
        text: Blog

format:
  html:
    theme: 
      - cosmo
      - "assets/theme.scss"
    highlight-style: monokai
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital@0;1&display=swap" rel="stylesheet">  
    toc: true
    mainfont: "Raleway"



