---
title: Aural Euphoria
author: Andy
date: '2022-11-21'
slug: []
categories:
  - Miscellaneous
subtitle: ''
description: ''
image: ''
showtoc: false
---


These are the liner notes for the *Aural Euphoria* playlist. I put this playlist together for my students, advisees, and colleagues who were all, to paraphrase Emo Philips, "born at a less comfortable distance from the apocalypse." This playlist is composed of a sample of songs that were a part of my musical education. It is by no means exhaustive, and I am sure I have omitted songs that should be here.

You should be able to find these gems on most music services, but there may be some that are lacking. I know that Garth Brooks is not available on Spotify. 


## The Early Years (Record 1 -- Side A)

As with any musical education, the artists and songs that resonated with me early on were a function of what my parents (especially my dad) listened to. This consisted of old country music, early R&amp;B, folk, and a lot of Elvis. My sister and I were weaned on the old 45s of Sam Cooke and Elvis. We also were exposed to a lot of old country music, learning songs by Tammy Wynette, Hank Snow, Charlie Pride, and Tom T. Hall, to name a few. But, by far and away, the two groups we heard the most of were Peter, Paul, &amp; Mary (my first concert at the ripe old age of three) and The Statkler Brothers (still might be my favorite band).

- Bring It On Home To Me (Sam Cooke; 1962)
- I Like Beer (Tom T. Hall; 1975)
- (Let Me Be Your) Teddy Bear (Elvis Presley; 1957)
- Puff the Magic Dragon (Peter, Paul, &amp; Mary; 1963)
- Thank You World (The Statler Brothers; 1974)
- Tijuana Jail (Kingston Trio; 1959)
- I Believe (When I Fall In Love It Will Be Forever) (Stevie Wonder; 1972)
- Tiny Dancer (Elton John; 1971)


**Honorable Mention**

- Elvira (Oak Ridge Boys; 1981)
- The Gambler (Kenny Rogers; 1978)
- Kiss An Angel Good Morning (Charlie Pride)
- Could I Have This Dance (Anne Murray; 1980)
- House At Pooh Corner (Loggins &amp; Messina; 1974)
- The Mosquito Song (Douglas Wood; 1980)
- Grandma's Feather Bed (Live) (John Denver; 1975)
- Mr. Tambourine Man (The Byrds; 1969)

<br />


## Junior High (Record 1 -- Side B)

As a bonafide product of Gen-X, I have a soft spot for early 80's music. This was the era where I got my first cassette tape (Weird Al Yankovic's *Dare To Be Stupid*) and started to listen to things my parents didn't approve of. I think I wore out several of these early cassettes, rewinding to replay a loved song over and over. Some of my favorites were Culture CLub's *Colour By Numbers*, Prince's *1999*, the Crüe's *Theatre of Pain*, The Boss' *Born In The U.S.A.*, and of course, Michael Jackson's *Thriller*.

- That's The Way (I'm Only Trying to Help You) (Culture Club; 1983)
- Beat It (Michael Jackson; 1982)
- Glory Days (Bruce Springsteen; 1984)
- Little Red Corvette (Prince; 1982)
- Smokin' In The Boys Room (Mötley Crüe; 1985)
- Glory of Love (Peter Cetera; 1986)


**Honorable Mention**

- Only You (Yazoo; 1982)
- Foolish Beat (Debbie Gibson; 1987)
- Manic Monday (The Bangles; 1986)
- Cum On Feel The Noize (Quiet Riot; 1983)
- I Wanna Rock (Twisted Sister; 1984)
- We've Got Tonight (Kenny Rogers; 1983)
- Next Time I Fall In Love (Peter Cetera &amp; Amy Grant; 1986)

<br />


## High School (Record 2 -- Side A)

The music I listened to in high school was far more heterogeneous and eclectic. Around this time is when rap and hip-hop started to trickle into my reportoire. Hair bands, synth pop, and early 90's country music dominated the radio, and what kind of teen would I be without a high dosage of emo?

- O.P.P. (Naughty By Nature; 1991)
- Friends In Low Places (Garth Brooks; 1990) -- Needs to have the extended verse
- Patience (Guns N' Roses; 1988)
- Misguided Angel (Cowboy Junkies; 1988)
- It's Tricky (Run-D.M.C.; 1986)
- The Promise (When In Rome; 1988)
- Friday I'm In Love (The Cure; 1992)
- King of Wishful Thinking (Go West; 1990)
- Bed Of Roses (Bon Jovi; 1992)
- Good Old Acappella (The Nylons; 1991)


**Honorable Mention**

- Going Back To Cali (LL Cool J; 1989)
- Every Rose Has Its Thorn (Poison; 1988)
- Walking In Memphis (Marc Cohn; 1991)
- Wipeout (The Fat Boys; 1987)
- If I Had A Boat (Lyle Lovett; 1988)
- It Takes Two (Rob Base &amp; DJ EZ Rock; 1988)
- The Dance (Garth Brooks; 1990)
- Blame It On The Rain (Milli Vanilli; 1989)
- Angel From Montgomery (John Prine &amp; Bonnie Raitt; 1990)
- Straight Outta Compton (N.W.A.; 1988)

<br />


## The College Years (Record 2 -- Side B)

College was a time of continued growth and and finding "new" music. During this time I also worked at The Electric Fetus in St. Cloud, and was exposed to all sorts of different artists. Grunge, a lot of indie artists, female bands, and Brit rock dominated the scene in this era.

- Yellow Ledbetter (Pearl Jam; 1991)
- Fade Into You (Mazzy Star; 1993)
- Hook (Blues Traveler; 1994)
- Common People (Pulp; 1995)
- Hobart Paving (Saint Etienne; 1993)
- Black Gold (Soul Asylum; 1992)
- It's The End Of The World As We Know It (And I Feel Fine) (R.E.M.; 1987)
- I'm On My Way (Proclaimers; 1988)
- She Don't Use Jelly (The Flaming Lips; 1993)


**Honorable Mention**

- Stay (Shakespeare's Sister; 1992)
- Rooster (Alice In Chains; 1992)
- Bizarre Love Triangle (New Order; 1986)
- Foolish Games (Jewel; 1995)
- She's Electric (Oasis; 1995)
- Go West (Pet Shop Boys; 1993)
- Say It Ain't So (Weezer; 1994)
- Independence Day (Martina McBride; 1993)
- Feed The Tree (Belly; 1993)
- Spin The Bottle (The Juliana Hatfield Three; 1993)



<br />


## Teaching High School (Record 3 -- Side A)

I taught high school math from 1998--2002. During this time period, I listened to a lot of soft rock (think Matchbox 20), harmonic female country acts, and dance oriented pop and hip-hop. I also got into U2 during this time for some reason. On the radio, teen pop got big.


- You Were Mine (Dixie Chicks; 1998)
- Because I Got High (Afroman; 2001)
- Show Me The Meaning Of Being Lonely (Backstreet Boys; 1999)
- I Want You To Want Me (Letters To Cleo; 1999)
- Stuck In A Moment You Can't Get Out Of (U2; 2000)
- Ride Wit Me (Nelly; 2000)
- No Frontiers (The Corrs; 1999)
- My Baby (Lil' Romeo; 2001)
- The Bad Touch (Bloodhound Gang; 1999)


**Honorable Mention**

- Lucky 4 You (Tonight I'm Just Me) (SHeDaAISY; 1999)
- MMMBop (Hanson; 1997)
- Never Ever (All Saints; 1997)
- Power of Goodbye (Madonna; 1998)
- What's Your Fantasy (Ludacris feat. Shawna; 2000)
- Jump Jive An' Wail (The Brian Setzer Orchestra; 1998)
- Hard Knock Life (JAY-Z; 1998)
- Sk8er Boi (Avril Lavigne; 2002)


<br />


## Graduate School (Record 3 -- Side B)

Moving to the Twin Cities for graduate school, I went to a lot of live music (back when a cover charge to most shows was $5). As such, I got into a lot more indie and alt-country music (although I still don't like Wilco). I also started listening to a lot more 70's era rock.


- My Generation (Part 2) (Todd Snider; 1994)
- Fields Of Gold (Eva Cassidy; 1998)
- Never Going Back Again (Fleetwood Mac; 1977)
- I'll Be Damned (Slobberbone; 1997)
- Baby One More Time (Travis; 1999)
- Say Yes (Elliott Smith; 1997)
- Amie (Damien Rice; 2003)
- Read 'Em And Weep (Junior Brown; 1998)
- Round And Round (Bob Schneider; 2002)
- The Cover Of "Rolling Stone" (Dr. Hook; 1972)


**Honorable Mention**

- One Toke Over The Line (Brewer &amp; Shipley; 1970)
- Fuck Her Gently (Tenacious D; 2001)
- All I Know (Art Garfunkel; 1973)
- Piss Up A Rope (Ween; 1996)
- Shooting Star (Bad Company; 1975)
- Everything Sux (Descendents; 1996)


<br />


## Teaching at UMN (Record 4 -- Side A)

The music that has been with me since I started my career at the University of Minnesota is more of the same genres that have been with me earlier. As I age, I definitely prefer songs and artists that are more melodic (no autotune!). I also have a penchant for more acoustic versions of songs. 

- Teach Your Children (Crosby, Stills, Nash &amp; Young; 1970)
- Denzel (Stephen Lynch; 2019)
- Ripple (Grateful Dead; 1970)
- Sin City (The Flying Burrito Brothers; 1969)
- Let's Duet (John C. Reilly &amp; Angela Correa; 2007)
- The Aeroplane (Tim Minchin feat. Asmara Feik; 2023)
- Emmylou (First Aid Kit; 2014)
- Challengers (The New Pornographers; 2007)
- Piece of Clay (Marvin Gaye; 1972)
- Where The Night Goes (Josh Ritter; 2015)


**Honorable Mention**

- Shambala (Three Dog Night; 1973)
- Lullaby (Josh Groban &amp; Ladysmith Black Mambazo; 2006)
- Strike The Bell (The Fisherman's Friends; 2018)
- Million Dollar Secret (Lucius; 2018)
- Time To Move On (Hi Ho Silver Oh; 2011)
- Fuck All The Perfect People (Chip Taylor &amp; The New Ukranians; 2012)
- Every Feeling (Ezra Furman; 2020)
- I Will Talk And Hollywood Will Listen (Robbie Williams; 2001)
- Betty (Taylor Swift; 2020)
- Gonna Make You Happy Tonight (Tripod; 2006)
- Crowded Table (The Highwomen; 2019)
- Sweet Baby James (Steep Canyon Rangers; 2020)
- Fields Of Athenry (The High Kings; 2010)
- Dancing On My Own (Robyn; 2010)


<br />


## A Love Letter To Minnesota Artists (Bonus Content)

These are some of my favorite songs from the bands that have called Minnesota home. 

- The Arms Of Orion (Prince; 1989)
- Surfin' Bird (The Trashmen; 1963)
- Don't Want To Know If You Are Lonely (Hüsker Dü; 1986)
- Cartoon (Soul Asylum; 1988)
- Stupid Boy (Gear Daddies; 1990)
- Is There Rock 'N' Roll In Heaven? (Slave Raider; 1988) 
- Blue (The Jayhawks; 1995)
- Love Untold (Paul Westerberg; 1996)
- What's On Your Mind (Pure Energy) (Information Society; 1988)
- Funkytown (Lipps Inc.; 1979)
- Toolmaster of Brainerd (Trip Shakespeare; 1989)
- DUI (Har Mar Superstar; 2004)
- Love Is The Law (Suburbs; 1984)
- (I Wanna Drive The) Zamboni (Gear Daddies; 1990)
- Can't Hardly Wait (The Replacements; 1987)
- Bruise Violet (Babes in Toyland; 1992)
- Closing Time (Semisonic; 1998)






